### PR TITLE
Add normalize_address normalize_prefix Jinja filters

### PR DESCRIPTION
**Pull request by matejv**
It would be useful to be able to have all parsed IP addresses in the same textual format.

Especially important to be able to use diff functions with IPv6 since some platforms may not follow recommendations in Section 4 of RFC 5952 (looking at you Cisco).

### CODE REVIEW

**Comment by dbarrosop** [comment]
Could you add unit tests for the jinja_filters? Something simple, like this:

https://github.com/napalm-automation/napalm-base/blob/develop/test/unit/TestHelpers.py#L268

Feel free to create the file `test/unit/test_jinja_filters.py` and put it there.

**Comment by matejv** [comment]
Something like this?

BTW: cidr_to_netmask filter returns the netmask as a netaddr.IPAddress object. Is this intentional or shall we convert to string before returning?

**Comment by matejv** [comment]
Added filter `prefix_to_addrmask` that will be used in translator for IOS

**Comment by dbarrosop** [comment]
> BTW: cidr_to_netmask filter returns the netmask as a netaddr.IPAddress object. Is this intentional or shall we convert to string before returning?

Yeah, we should convert to string for consistency with your additions. Would you mind fixing in this PR now that you are at it? :P

Thanks for adding tests to the already existing filters!

**Comment by matejv** [comment]
No problem, done! :)

**Pull request merged**
