### PR TITLE
Missing mapping handling

### PR DESCRIPTION
**Pull request by pierky**
Scenario: an interface type is not covered by the rule's map:

```
interface TenGigabitEthernet0/0/0
 description To heaven
 ip address 192.0.2.1 255.255.255.0
```

```
    type:
	_process:
	    - value: "{{ interface_key }}"
	      regexp: "(?P<value>(\\w|-)*)\\d+"
	      map:
		  fastethernet: ethernetCsmacd
		  gigabitethernet: ethernetCsmacd
		  management: ethernetCsmacd
		  loopback: softwareLoopback
		  port-channel: ieee8023adLag
		  vlan: l3ipvlan
```

Before this:

```
...
  File "/home/pierky/napalm-yang/napalm_yang/parsers/base.py", line 151, in parse_leaf
    result = self._parse_leaf_default(attribute, m, data)
  File "/home/pierky/napalm-yang/napalm_yang/parsers/text_tree.py", line 113, in _parse_leaf_default
    return super()._parse_leaf_default(attribute, mapping, data)
  File "/home/pierky/napalm-yang/napalm_yang/parsers/jsonp.py", line 110, in _parse_leaf_default
    d = mapping['map'][d.lower()]
KeyError: u'tengigabitethernet'
```

After this:

**napalm-yang - ERROR - Wrong value for type: TenGigabitEthernet**

```
  File "/home/pierky/napalm-yang/napalm_yang/parser.py", line 95, in _parse
    self._parse_leaf(attribute, model, mapping)
  File "/home/pierky/napalm-yang/napalm_yang/parser.py", line 188, in _parse_leaf
    setter(value)
  File "/home/pierky/napalm-yang/napalm_yang/models/openconfig/interfaces/interface/config/__init__.py", line 131, in _set_type
    n:ietf:params:xml:ns:yang:iana-if-type', '@module': u'iana-if-type'}, u'fibreChannel': {'@namespace': u'urn:ietf:params:xml:ns:yang:iana-if-type', '@module': u'iana-if-type'}, u'ift:dvbRcsTdma': {'@namespace': u'urn:ietf:params:xml:ns:yang:iana-if-type', '@module': u'iana-if-type'}, u'ianaift:transpHdlc': {'@na
...
ValueError: {'error-string': 'type must be of a type compatible with identityref', 'generated-type': 'YANGDynClass(base=RestrictedClassType(base_type=unicode, restriction_type="dict_key", restriction_arg={u\'ift:mpegTransport\': {\'@namespace\': u\'urn:ietf:params:xml:ns:yang:iana-if-type\', \'@module\': u\'iana-if-type\'}, u\'ift:qam\': {\'@namespace\': u\'urn:ietf:params:xml:ns:yang:iana-if-type\', \'@module\': u\'iana-if-type\'}, u\'ift:q2931\': {\'@namespace\': u\'
...
```

### CODE REVIEW

**Comment by dbarrosop** [comment]
Sorry for the late response, october was crazy... I think we should just add `tengigabitethernet` to the map.

**Comment by pierky** [comment]
Yes of course, that would solve the problem too; my intention was to "properly" handle those cases where a mapping was not found by raising a more descriptive exception than the builtin KeyError. But don't know if this makes sense nor if the code I suggested could break anything else.

**Comment by dbarrosop** [comment]
If we want to control the error thrown we should do something like:

```
if d and "map" in mapping:
    try:
        d = mapping['map'][d.lower()]
    except KeyError:
        raise KeyError("my error goes here")
```

But I'd rather leave that out. I think the error we get now is slightly more descriptive than what pyangbind throws. I also want as little code as possible in the parser as the code here is called thousands of times while parsing so efficiency is desirable.

**Comment by pierky** [comment]
Efficiency wins! Thanks for the detailed feedback, going to close this.

**Comment by dbarrosop** [comment]
Feel free to send a PR fixing any missing key we may have :)

**Pull request closed without merging**
