### PR TITLE
IOS-XE OpenConfig/RESTCONF mapping - oc-interfaces

### PR DESCRIPTION
**Pull request by nickethier**
WIP

Initial work at a mapping for IOS-XE using Cisco's OpenConfig model support over RESTCONF. 

Also adds a timestamp filter (and test) to support Cisco's deviation to how they represent timestamps. 

This PR specifically aims to implement the oc-interface module for both config and state models.

### CODE REVIEW

**Comment by nickethier** [comment]
Requires napalm-automation/napalm-base#301

**Comment by dbarrosop** [comment]
@nickethier I merged the PR and released a new `napalm-base` version.

**Comment by nickethier** [comment]
There are several bugs I've ran into (and reported) with the RESTCONF api on ios, so I've put this effort on hiatus. I'll reopen if I do any additional work here.

**Comment by dbarrosop** [comment]
Sad to hear :(

Thanks for the update.

**Pull request closed without merging**
