### PR TITLE
Fixes interface type parsing

### PR DESCRIPTION
**Pull request by yapengwu**
This commit is the change for comment I made for issue #158

### CODE REVIEW

**Comment by dbarrosop** [comment]
This change doesn't seem correct and it's breaking the tests. Try the following though:

```
(?P<value>(\\D|-)*)\\d+
```

I did some tests and looks like it does trick.

**Comment by dbarrosop** [comment]
Did you get the chance to look at this?

**Comment by yapengwu** [comment]
@dbarrosop how to run the check test in my own repo? thanks. I will make the fix for this error.

**Comment by dbarrosop** [comment]
You should be able to run the tests with `pytest test/`

**Pull request merged**
