### PR TITLE
Documenting new API

### PR DESCRIPTION
**Pull request by dbarrosop**
I will be basically revamping entirely the documentation but wanted to make sure the DSL was as simple as possible and I think we are getting there so I want to focus first on the examples/use cases and then I will be revamp the rest.

I added tests for the major use cases when parsing lists and built a framework to generate docs from them. You can see the results here:

https://napalm-yang.readthedocs.io/en/dbarrosop-documentation/yang/parsers/examples_list.html

### CODE REVIEW

**Comment by dbarrosop** [comment]
@matejv This might be useful for you if you are trying to write `network-instances` for ios with the `TextTree`.

**Comment by matejv** [comment]
These examples are a big help. Kudos!

It's still confusing when you dive into more complex parsing, but much better that the old parser.

**Comment by dbarrosop** [comment]
> It's still confusing when you dive into more complex parsing, but much better that the old parser.

I agree but I think by adding support to the `network-instances` model we are already dealing with most of the complexity. The rest should be much easier to deal with I think so I have hopes this won't get out of hand.

**Comment by matejv** [comment]
Yea, that's why I started with static-routes - if it can parse that it will be able to handle almost anything you can imagine the rest.

BTW - can I do this somehow:

```yaml
    next-hops:
        _process: unnecessary
        next-hop:
            _process:
                - path: "?interface_ref.?next_hop_addr"
                  regexp: "^(?P<value>(?P<interface_ref>[a-zA-Z][\\w\\-/]+(?::\\d+)?(?:\\.\\d+)?)\\s(?P<next_hop_addr>(?:\\d+\\.\\d+\\.\\d+\\.\\d+|[0-9a-fA-F:]+:[0-9a-fA-F:]+)))$"
                  key: "{{ interface_ref }} {{ next_hop_addr|normalize_address }}"
                - path: "?next_hop_addr"
                  regexp: "^(?P<value>(?P<next_hop_addr>(?:\\d+\\.\\d+\\.\\d+\\.\\d+|[0-9a-fA-F:]+:[0-9a-fA-F:]+)))$"
                  key: "{{ next_hop_addr|normalize_address }}"
                - path: "?interface_ref"
                  regexp: "^(?P<value>(?P<interface_ref>[a-zA-Z][\\w\\-/]+(?::\\d+)?(?:\\.\\d+)?))"
                  key: "{{ interface_ref }}"
                  when: "{{ extra_vars.next_hop_addr is not defined }}"
```

Basically I want to apply the last rule only if neither of the first two matched. Not sure what I could put into `when:` to check for that.

**Comment by dbarrosop** [comment]
So I think your `when` is not correct but the idea is, I think. Try:

```
when: "{{ not extra_vars.get('next_hop_addr', None) }}"
```

**Comment by matejv** [comment]
Ah, no, figured it out - it can't be done this way.

[`parse_list`](https://github.com/napalm-automation/napalm-yang/blob/586b5a1ac0fdbc1e7e640502c4dbfb9eea14a195/napalm_yang/parsers/base.py#L78) in `base.py` runs `resolve_rule` with all three rules and that translates Jinja templates under `when` for all three.

Only after that does `parse_list` go through each rule and calls `resolve_path` and `_parse_leaf_default` which in turn evaluates the `regex` that fills `extra_vars`.

So anything I put in `when` will have access to vars from previous containers, but not from this one.

I'll have to figure something else.

**Comment by dbarrosop** [comment]
Ok, would you mind opening an issue with the description of the problem and some examples? I will take a look myself and give you a hand.

**Comment by matejv** [comment]
See #81 Hopefully `006_ios_ip_route/example.yaml` makes it clear what I'm trying to do.

**Comment by dbarrosop** [comment]
Not yet complete but merging anyway

**Pull request merged**
